### ISSUE TITLE
Break out SiteTree in GridField into own module

### ISSUE THREAD

**Issue by Zauberfisch** [micmania1/silverstripe-blogger#27]
http://logs.simon.geek.nz/index.php?date=2014-07-18#log_1349218

**Comment by micschk** [comment]
@Zauberfisch, I think this module does what you're after: https://github.com/micschk/silverstripe-gridfieldpages

**Comment by Zauberfisch** [comment]
@micschk indeed, I have actually seen that already, but that was after @micmania1 has created the lumberjack module.
I haven't tested either of those modules yet though, will have to delay that until I have a project that requires it.

@micmania1 should we close the issue now?

**Comment by micschk** [comment]
@Zauberfisch that's too bad, it's been there for a while. Updated it and improved the readme today, maybe it will get picked up a bit better.

@micmania1 seems we've been doing the same job :)

**Comment by stevie-mayhew** [comment]
@micschk - as have I https://github.com/Little-Giant/silverstripe-catalogmanager

Seems like its something we all wanted :smile:

**Comment by micschk** [comment]
@stevie-mayhew - that looks pretty solid as well!

**Comment by micmania1** [comment]
This is on 2.0 branch: https://github.com/micmania1/silverstripe-blogger/tree/2.0 \o/
